### ISSUE TITLE
Need to set REST function call for AINFT Factory 

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#1183]

**Comment by woomurf** [comment]
@platfowner Is this for a REST function registered in the manage_app route to handle app creation events in AINFT Factory?

**Comment by platfowner** [comment]
> @platfowner Is this for a REST function registered in the manage_app route to handle app creation events in AINFT Factory?

Yes, I'll share a draft PR soon.

**Comment by woomurf** [comment]
we decided using registerApp function after createApp. so i think this REST function is not required. how do you think this?

**Comment by platfowner** [comment]
> we decided using registerApp function after createApp. so i think this REST function is not required. how do you think this?

Oh, so now it's the user's responsibility to maintain the consistency of the app id reservation between the blockchain and the firebase backend? If it's the case, I'll cancel this task.

**Comment by woomurf** [comment]
yes. ainft server will not support create app. User have to create app in ain blockchain and then register app to ainft server.

**Comment by platfowner** [comment]
> yes. ainft server will not support create app. User have to create app in ain blockchain and then register app to ainft server.

Got it. Thanks! 👍

**Comment by platfowner** [comment]
Obsolete issue.
