### ISSUE TITLE
Better logging with module prefixes

### ISSUE THREAD

**Issue by liayoo** [ainblockchain/ain-blockchain#128]
It would be nice to have a programmatic way to set prefixes for logs. Couldn't find an easy way to set each function's name, but I think we can set the file names at least.

For example:
logger.info(\`[${P2P_PREFIX}] Listening to peer-to-peer connections on: ${P2P_PORT}\n\`);
=> logger.info(\`Listening to peer-to-peer connections on: ${P2P_PORT}\n\`);

Refs:
https://stackoverflow.com/questions/42858585/add-module-name-in-winston-log-entries
https://stackoverflow.com/questions/13410754/i-want-to-display-the-file-name-in-the-log-statement

**Comment by platfowner** [comment]
Resolved.
