### ISSUE TITLE
[BUG] os.version is not a function

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#181]
**Describe the bug**
I do not know when it started tho, I presume it caused by node version?

**To Reproduce**
Have no idea.

**System information:**
 - OS & version: OSX
 - Node version: 10.x

**Comment by platfowner** [comment]
Which version was used? In 0.5.1, it requires >12 node version: https://github.com/ainblockchain/ain-blockchain/blob/develop/package.json#L13

**Comment by minsulee2** [comment]
@platfowner I updated it to >12 tho, it somehow does not work. I will check this out again soon.

**Comment by minsulee2** [comment]
still not working in >12 node version.

**Comment by platfowner** [comment]
We don't have strong use cases for os.version yet. So, feel free to remove it if necessary.

**Comment by platfowner** [comment]
Short term solution: Commented it out.

**Comment by platfowner** [comment]
The code was commented out from getRuntimeInfo().
Let me close this for now.
