### ISSUE TITLE
[BUG] error: [BLOCKCHAIN] First block is not the Genesis block

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#182]
**Describe the bug**
When the first node is started and nobody comes, after that, terminates the first node and restart! then it faces error :(

**To Reproduce**
1. [Tracker] node tracker-server/index.js
2. [Node1] NUM_VALIDATORS=2 ACCOUNT_INDEX=0 HOSTING_ENV=local node client/index.js
3. [Node2] DO NOTHING
4. [Node1] ctrl + c (terminate the node)
5. [Node1] NUM_VALIDATORS=2 ACCOUNT_INDEX=0 HOSTING_ENV=local node client/index.js again

**Expected behavior**
The [Node1] should be wait for other nodes in a peaceful manner.

**Comment by platfowner** [comment]
Caused by created_at field newly introduced recently to Transaction class.

**Comment by liayoo** [comment]
Fixed by #189
