### ISSUE TITLE
[BUG] error: [BLOCKCHAIN] First block is not the Genesis block

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#183]
**Describe the bug**
This appears when trying to restart a node sometimes.

**To Reproduce**
1. During running blockchain network(I mean several nodes are communicating with one another)
2. Stop one node
3. restart it right after the step 2

**Expected behavior**
The error shouldn't be gone off when a node is restarted.

**Comment by platfowner** [comment]
Transaction hash changes due to created_at field newly introduced recently to Transaction class.

**Comment by liayoo** [comment]
Fixed by #189
