### ISSUE TITLE
[BUG] Txs with strictly ordered nonces are dropped

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#213]
**To Reproduce**
1.  Remove `nonce: -1` line in `setUp()` of sharding.test.js
2. Run ./node_modules/mocha/bin/mocha --timeout 320000 integration/sharding.test.js -g 'set_value with is_global = false'

It shows:
```
Iteration count exceeded its limit before the given tx 0x064be9ad56c513d348e30664ebd151ac0fb29eb3302775322487d944cbc2e3c1 is finalized!
Failed to check finalization of cleanUp() tx.
```

This is due to the transaction sent by `setUp()` is dropped with mismatched nonce.

Also, the following test run shows no such error message:
```
./node_modules/mocha/bin/mocha --timeout 320000 integration/node.test.js -g 'set_value'
```

This is because of another bug that when there is only one element in `orderedUnvalidatedTransactions` variable in `getValidTransactions()` of tx-pool/index.js, the nonce checking is skipped:
```
while (orderedUnvalidatedTransactions.length > 1) {
```

**Comment by liayoo** [comment]
Fixed in #281
