### ISSUE TITLE
Tracker server log error

### ISSUE THREAD

**Issue by pengin7384** [ainblockchain/ain-blockchain#25]
![image](https://user-images.githubusercontent.com/32831939/88503885-e8f8e780-d00d-11ea-8cb8-a60c6a21d396.png)
There are undefined log messages in tracker server.

**Comment by pengin7384** [comment]
I'm working on this issue

**Comment by minsulee2** [comment]
Can you close the issue if it's been resolved?

**Comment by pengin7384** [comment]
Closed! Thanks
