### ISSUE TITLE
[BUG] Need to be able to revert changes made in native functions

### ISSUE THREAD

**Issue by liayoo** [ainblockchain/ain-blockchain#265]
Currently, native function failures do not bubble up, which means state changes made in native functions are not reverted when function execution fails. 

Related TODO: https://github.com/ainblockchain/ain-blockchain/pull/262/files#diff-c581d39cccd0f924d890ba5d28f2c97e4a5d5385cb1c7d3c0a27187d8b2c94b4R609

**Comment by platfowner** [comment]
Fixed.
