### ISSUE TITLE
ain_getBlockList limitation

### ISSUE THREAD

**Issue by cshcomcom** [ainblockchain/ain-blockchain#293]
When user calls ain_getBlockList, all blocks are queried. This causes program termination. We need limitation of ain_getBlockList!

**Comment by liayoo** [comment]
fyi, there's a similar api [client/index.js](https://github.com/ainblockchain/ain-blockchain/blob/develop/client/index.js#L286)! It'd be nice if we could have something similar in the json rpc API as well!

**Comment by cshcomcom** [comment]
@liayoo Thanks! I will change it with your good reference!

**Comment by platfowner** [comment]
Fixed.
