### ISSUE TITLE
[BUG] Node 4 doesn't work

### ISSUE THREAD

**Issue by cshcomcom** [ainblockchain/ain-blockchain#348]
**To Reproduce**
1. Run 'sh start_servers.sh'
2. Node 4 does nothing!

**Screenshots**
![image](https://user-images.githubusercontent.com/74223287/115501051-76235100-a2ad-11eb-8176-0e698a5f998c.png)

**Additional context**
There seems to be something wrong with 'start_servers.sh' script being changed!
There was no problem before #333

**Comment by minsulee2** [comment]
@cshcomcom closing it?

**Comment by platfowner** [comment]
@minsulee2 Could you create a quick PR to alter the limit values to MIN_NUM_VALIDATORS - 1?
