### ISSUE TITLE
[Discussion] inbound and outbound max numbers

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#354]
As we have discussed about it tho, there has been some issues how to fix the numbers and initially set it up. Furthermore, the extension of network should also be considered for the near future.

Should do:
- decide initial connection numbers
- real max number possibly handle nodes
- consider extension of the size of network

**Comment by platfowner** [comment]
Currently, we're using "TARGET_NUM_OUTBOUND_CONNECTION": 3, and "MAX_NUM_INBOUND_CONNECTION": 6
Thanks!
