### ISSUE TITLE
[BUG] Stuck in the Needs syncing... phase

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#432]
Error occurred:

- Stop all nodes(5 of them)
- Start with node 0 (block num 298)
- Start with node 1 (block num 299)
- Start with node 2 (block num 299)
- Start with node 3 (block num 297)
- Start with node 4 (block num 297)
- Show Needs syncing... message from the nodes 1, 2
- Work 0, 3, 4 correctly
- Enable to rerun and the cluster works correctly when restarting either node1 or node2 at least

It caused because of the stucking nodes have got higher number than the first deploying node(node0 here) but `BlockchainNodeStates` cannot get into the SERVING state.

**Comment by platfowner** [comment]
Maybe duplicates: https://github.com/ainblockchain/ain-blockchain/issues/562

**Comment by platfowner** [comment]
Let me fix it.
