### ISSUE TITLE
Need a limit on per-app state tree size

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#487]
We need a limit on per-app state tree size to avoid malicious state tree size increase.

Offline discussion:
- MAX_STATE_TREE_SIZE_PER_BYTE or MIN_BYTES_PER_STATE_NODE to get allowed max per-app state tree size from per-app state tree bytes

**Comment by liayoo** [comment]
Implemented in https://github.com/ainblockchain/ain-blockchain/pull/504
