### ISSUE TITLE
Need APIs for blockchain state utilization

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#498]
We need blockchain APIs for state usage for users e.g.
- ain_getStateUsage(), /get_state_usage()
- params: app_name = ‘collaborative_ai’ 

and ain-js APIs as well.

**Comment by liayoo** [comment]
APIs added: https://github.com/ainblockchain/ain-blockchain/pull/515

**Comment by platfowner** [comment]
ain-js update is needed. @cshcomcom

**Comment by platfowner** [comment]
ain-js updated: https://github.com/ainblockchain/ain-js/pull/38
