### ISSUE TITLE
Need to apply more precise db path validation logic

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#50]
- Allow:
  '/a/.b'
  '/a/$b'
  '/a/\*'

- Not allow:
  '/a/.'
  '/a/$'
  '/a/b.'
  '/a/b$'
  '/a/b.c'
  '/a/b$c'
  '/a/\*b'
  '/a/b\*'
  '/a/b\*c'

**Comment by minsulee2** [comment]
what is the last two '/a/b' and '/a/b' in Not allow difference?

**Comment by platfowner** [comment]
@minsulee2 Ah, it's MD language issue. Just fixed.

**Comment by minsulee2** [comment]
Thanks for answering :)
