### ISSUE TITLE
Need to apply path validation to object-to-write

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#51]
- Allow:
```
{
  '.a': 'x'
}
{
  '*': 'x'
}
```

- Not allow:
```
{
  '.': 'x'
}
{
  'a.': 'x'
}
{
  'a.b': 'x'
}
{
  '*a': 'x'
}
{
  'a*': 'x'
}
{
  'a*b': 'x'
}
```

Full list of reserved characters: https://docs.ainetwork.ai/ai-network-design/blockchain-database/states/predefined-structures

**Comment by minsulee2** [comment]
Does it mean not to allow ref with char '.'?

**Comment by platfowner** [comment]
@minsulee2  Yes, the same policy applied to the db path will be applied to the state object: https://github.com/ainblockchain/ain-blockchain/issues/50

**Comment by minsulee2** [comment]
Indeed! edited one is way clearer!! thanks for the updates!
