### ISSUE TITLE
[DISCUSSION] Stuck in Needs syncing....

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#562]
The blockchain network can be stuck when some lazy nodes take the blockchain network first and the others come and join the network later on.

Scenario
1. most of nodes is down.
2. Some lazy nodes reboot their nodes and join the network earlier than latest nodes.
3. The lazy nodes set their state `serving`.
4. The later joining nodes are stuck in `Needs syncing....`.

**Comment by platfowner** [comment]
Let me close it.
