### ISSUE TITLE
[BUG] Rule attack with `process.exit()` function

### ISSUE THREAD

**Issue by cshcomcom** [ainblockchain/ain-blockchain#614]
**Describe the bug**
When I set the rule to `'write': 'process.exit(1)',` and send SET_VALUE tx, the node died.

**Screenshots**
![image](https://user-images.githubusercontent.com/74223287/136885833-ef138d14-d137-49a8-af8d-9f44ef61a34f.png)

**Comment by platfowner** [comment]
Fixed.
