### ISSUE TITLE
[BUG] Increase of memory usage by https://github.com/ainblockchain/ain-blockchain/pull/684

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#685]
Increase of memory usage observed due to the following PR:
https://github.com/ainblockchain/ain-blockchain/pull/684

Grafana snapshots AFTER:

![block_number_after](https://user-images.githubusercontent.com/46211617/141480306-a5e38571-f3b9-4a7e-803a-018944509264.jpg)

![memory_usage_after](https://user-images.githubusercontent.com/46211617/141480332-a54dee37-a00f-4ac0-b1c7-76592bac6227.jpg)

Grafana snapshots BEFORE:

![memory_usage_before](https://user-images.githubusercontent.com/46211617/141480375-bffc4d50-aa40-4149-917c-05b4ca4047a9.jpg)

**Comment by platfowner** [comment]
error_logs.txt
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa1a640 node::Abort() [node]
 2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9a62e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9a9a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd57c25  [node]
 6: 0xd582b6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd64b75 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [nod
e]
 8: 0xd65a25 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReaso
n, v8::GCCallbackFlags) [node]
 9: 0xd684dc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::Alloca
tionOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd2face v8::internal::Factory::NewFixedArrayWithHoles(int, v8::internal::AllocationType) [node]
11: 0x110512a v8::internal::FixedArrayBuilder::EnsureCapacity(v8::internal::Isolate*, int) [node]
12: 0x1095dfc  [node]
13: 0x1097c91 v8::internal::Runtime_RegExpExecMultiple(int, unsigned long*, v8::internal::Isolate*) [node]
14: 0x140dc19  [node]
```

**Comment by liayoo** [comment]
Thanks for reporting the issue!! I've looked into it and suspect it was caused by several bugs in consensus, which prevented from finalizing chains, filling up the block pools with blocks and snapshots. I fixed them in 098d12f, 3a122b5, and 6a10b1d, but will keep looking if this issue persists.

**Comment by platfowner** [comment]
Now it seems the issue is gone after latest patches.

Grafana snapshots AFTER PATCH:

<img width="1110" alt="block_number_after_patch" src="https://user-images.githubusercontent.com/46211617/141709665-1edc5bff-00c4-492a-89be-7023de500509.png">

<img width="558" alt="memory_usage_after_patch" src="https://user-images.githubusercontent.com/46211617/141709670-95776c53-6abb-432e-8716-1485f8843665.png">

**Comment by platfowner** [comment]
Fixed.
