### ISSUE TITLE
Need ddos protection

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#690]
We need ddos protection for the express server.

**Comment by minho-comcom-ai** [comment]
public-facing domain?
- [GCP Cloud Armor](https://console.cloud.google.com/net-security/securitypolicies/list)
- Cloudflare?

**Comment by platfowner** [comment]
https://www.npmjs.com/package/express-rate-limit

**Comment by platfowner** [comment]
Added basic implementation.
