### ISSUE TITLE
Support latest OSs

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#692]
Scope:
- Support <= macOS latest image
- Support <= Ubuntu 18.04

**Comment by shyun-comcom** [comment]
Tests (integration, unit) were completed in Ubuntu `20.04` (with node `16.13.1`).

```
shyun@instance-1:~/ain-blockchain$ uname -a
Linux instance-1 5.11.0-1022-gcp #24~20.04.1-Ubuntu SMP Thu Oct 21 16:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by minsulee2** [comment]
This has been also supported in Github actions!
