### ISSUE TITLE
[BUG] tx-pool unit test broken?

### ISSUE THREAD

**Issue by cshcomcom** [ainblockchain/ain-blockchain#696]
**Description**
Nothing happen after `npm run test_unit_tx_pool`

**To Reproduce**
1. `npm run test_unit_tx_pool`

**Screenshots**
![image](https://user-images.githubusercontent.com/74223287/142340001-df3952d0-2f00-4218-a265-e835db4ff7d2.png)

**Comment by shyun-comcom** [comment]
Fixed with #751!
