### ISSUE TITLE
Npm package install issue on Mac

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#7]
I think most of you guys do not have a problem with installing npm packages to run ain-blockchain though (it is automatically done with 'npm install' by the way), it may not be the case with the 'diskusage' package.

For the Mac users, if you have any troubles with it, please use this command 'xcode-select --install'.
For whom still have the problem with this if you already install xcode-select sutff, then 'sudo rm -rf $(xcode-select -print-path)' and reinstall xcode-select with this command 'xcode-select --install'.

Please feel free to ask any questions if you have any issues regarding on this!
Many thanks!

**Comment by platfowner** [comment]
Need to update README.md with nvm + yarn install.

**Comment by minsulee2** [comment]
@platfowner I will update README.md soon.

**Comment by minsulee2** [comment]
This has resolved with yarn packages and node version >= 12.
