### ISSUE TITLE
Migrate tracker server communication to less heavy methods

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#718]
We don't need heavy web socket communication channels between the blockchain nodes and the tracker server.
I think we can migrate to one way communication methods such as json rpc or other rest apis.

**Comment by platfowner** [comment]
Just realized that address is not verified in the updateNodeInfo() of the tracker server.
@minsulee2  Could you take a look?

**Comment by platfowner** [comment]
> Just realized that address is not verified in the updateNodeInfo() of the tracker server. @minsulee2 Could you take a look?

Also, what about adding protocol version for tracker, e.g. TRACKER_PROTOCOL_VERSION to constants.js like DATA_PROTOCOL_VERSION? cc: @liayoo @cshcomcom

**Comment by minsulee2** [comment]
@platfowner Yeah, I am working on it in other branch now. A fix will be upcoming PR soon.
