### ISSUE TITLE
[BUG] REST function call doesn't work

### ISSUE THREAD

**Issue by cshcomcom** [ainblockchain/ain-blockchain#734]
**Describe the bug**
- REST function looks like broken in the latest version of the develop branch.
- Test environment is `Merge pull request #722 from ainblockchain/bugfix/liayoo/node-restart-sync liayoo* 24/11/2021, 7:14 오후` (`3c3afcbf554c0f99b2334f57bf793181a5fb2f9c`)

**To Reproduce**
1. `node tools/startMockWorker.js`
2. `node tools/sendCreateAppTx.js`
3. `node tools/sendSetFunctionTx.js`
4. `node tools/sendSetRuleTx.js`
5. `node tools/sendTaskRequestTx.js`
6. Nothing happens

**Comment by platfowner** [comment]
@cshcomcom Did you test it on GCP or on local?

**Comment by cshcomcom** [comment]
I tested it on local and @shyun-comcom tested it on GCP

**Comment by cshcomcom** [comment]
Local environment I forgot that ENABLE_REST_FUNCTION_CALL was false. Let's retest on GCP. @shyun-comcom

**Comment by platfowner** [comment]
> Local environment I forgot that ENABLE_REST_FUNCTION_CALL was false. Let's retest on GCP. @shyun-comcom

Right, let me update local scripts though.

**Comment by shyun-comcom** [comment]
To change genesis configuration (such as DEFAULT_DEVELOPERS_URL_WHITELIST and DEFAULT_CORS_WHITELIST), it needs to create new genesis block (`blockchain-configs/{chain-name}/genesis_block.json.gz`) using `tools/genesis-file/createGenesisBlock.js` script.

Creating new genesis block solved this problem.
