### ISSUE TITLE
[BUG] Cannot setup via setup_blockchain_ubuntu.sh

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#765]
Node v12 cannot be installed.

Error occurred when running `sudo apt update` or `curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -`
```
...
Err:1 https://deb.nodesource.com/node_12.x bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY
...
```

**Comment by minsulee2** [comment]
Solution I found in https://github.com/nodesource/distributions/issues/1227
```
sudo rm -rf /var/lib/apt/lists/*
sudo rm -rf /etc/apt/sources.list.d/*
sudo apt-get update
```

**Comment by platfowner** [comment]
@minsulee2  Hmm.. i'm afraid it looks like a too much aggressive approach. could you try to search wider before actually executing it?

**Comment by platfowner** [comment]
@minsulee2  what about trying this?
`curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -`

https://github.com/nodesource/distributions/issues/1181


We're already using a similar solution for monitoring:
https://github.com/ainblockchain/ain-blockchain/blob/develop/setup_monitoring_ubuntu.sh#L52

**Comment by liayoo** [comment]
fyi, I just encountered the same error in sandbox node 97. Tried the following but none of them worked (still worth trying if you ever see this issue again..):
- `curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -`
- `sudo chmod +644 /usr/share/keyrings/nodesource.gpg` ([link](https://github.com/nodesource/distributions/issues/1227#issuecomment-887645091))
- Adding the missing pub key ([link](https://askubuntu.com/a/358424))

Finally was able to install node-js after uninstalling it first:
```
sudo apt-get purge nodejs
sudo rm -r /usr/lib/node_modules/
sudo rm -r /etc/apt/sources.list.d/nodesource.list
```
