### ISSUE TITLE
waitUntilTxFinalized causes infinite stuck when running integration test

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#77]
I ran the below command
```
./node_modules/mocha/bin/mocha ./integration/dev.test.js --timeout 160000
```
and I've got stuck forever since waitUntilTxFinalized function in setUp() never finishes.

**Comment by minsulee2** [comment]
Hmm, I wonder it only happens to me.

**Comment by platfowner** [comment]
Oh, I'm not quite sure but maybe I have the fix in my branch: https://github.com/ainblockchain/ain-blockchain/compare/develop...feature/platfowner/global_path 
- https://github.com/ainblockchain/ain-blockchain/commit/61f36cba84c6725bd566f1d0564d004a0a2ec04c
- https://github.com/ainblockchain/ain-blockchain/commit/d7a494c523059b4a7713c7043fd1bdc8600ba8e3

The PR will arrive sooner or later.

**Comment by minsulee2** [comment]
I found the reason myself why it breaks in the end. That's just because node version 12.x.x does not support 'system-sleep' package!! After downgrading node version to 10.15.3, All tests have run correctly. I also updated README at #73 . The package issue needs to be tracked in case of upgrading node version in the near future. cc: @platfowner @liayoo

**Comment by platfowner** [comment]
Node version was upgraded to 12.x and it's gone.
But we have some other issues: #213
