### ISSUE TITLE
Npm package vulnerabilities tracking

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#8]
Now, there are 14 vulnerabilities are detected. In these vulnerabilities, there is one thing needs to be fixed as soon as possible, that is the '@ainblockchain/ain-util' package. it may cause 'Regular Expression Denial of Service'.
The rest of 13 vulnerabilities are caused from the 'lodash' package. Since they are **low** vulnerabilities and have not been patched yet. it may be good enough for tracking them down.

Feel free to ask any questions if you have!
Many thanks!

**Comment by minsulee2** [comment]
Almost all of vulnerabilities are updated and fixed.
Now, only one left on @ainblockchain/ain-util, that is acorn one.

I will keep track this.
Many thanks!

**Comment by liayoo** [comment]
Related: https://github.com/bitchan/eccrypto/pull/54

**Comment by liayoo** [comment]
Last vulnerability issue fixed in #68
