### ISSUE TITLE
[BUG] createGenesisBlock.js fails for non-zero chain_id 

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#845]
createGenesisBlock.js fails for non-zero chain_id in genesis params with error message:
```
RESULT: {"gas_amount_total":{"bandwidth":{"service":2},"state":{"service":0}},"gas_cost_total":0,"result_list":{"0":{"code":0,"bandwidth_gas_amount":1},"1":{"message":"Trying to write owner-only function: _openCheckin","code":10404,"bandwidth_gas_amount":1}}}
```

**Comment by liayoo** [comment]
Could you check if you updated the genesis_addr in blockchain_params.json? (there are some other values that need changing as well but it seems this would cause that specific error)

**Comment by platfowner** [comment]
> Could you check if you updated the genesis_addr in blockchain_params.json? (there are some other values that need changing as well but it seems this would cause that specific error)

Yes, surely it was. Let me proceed with chain_id = 0 and share the config files soon.

**Comment by platfowner** [comment]
Fixed, thanks!
