### ISSUE TITLE
cd .. in setup_tracker_gcp.sh doesn't work

### ISSUE THREAD

**Issue by liayoo** [ainblockchain/ain-blockchain#87]
Can we fix this so that we can actually be in ../ain-blockchain after setting everything up?

**Comment by liayoo** [comment]
Maybe we can just tweak the commands in README.md? (ref: https://askubuntu.com/questions/481715/why-doesnt-cd-work-in-a-shell-script)

**Comment by platfowner** [comment]
fixed.
