### ISSUE TITLE
Need to optimize getStateFreeTierUsage()

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#915]
Just realized that we have a loop in getStateFreeTierUsage():
```
    const apps = DB.getValueFromStateRoot(this.stateRoot, PredefinedDbPaths.APPS, true) || {};
    for (const appName of Object.keys(apps)) {
    ...
```

and this function is called for every tx operation.

**Comment by liayoo** [comment]
Fixed in https://github.com/ainblockchain/ain-blockchain/pull/959
