### ISSUE TITLE
[BUG] Integration test breaks

### ISSUE THREAD

**Issue by platfowner** [ainblockchain/ain-blockchain#996]
How to reproduce:
Turn off the disable_tx_receipt_recording timer flag in blockchain-configs/base:
```
  "disable_tx_receipt_recording": {
    "enabled_block": null,
    "has_bandage": false,
    "_note": "Remove this flag or set disabled_block to 2 if you need to run with the tx receipt recording feature"
  }
```
and run
```
yarn run test_integration_node
```

Error messages:
```
yarn run v1.22.10
$ BLOCKCHAIN_CONFIGS_DIR=blockchain-configs/3-nodes ./node_modules/mocha/bin/mocha --timeout 640000 test/integration/node.test.js
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording


  Blockchain Node
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /Users/seo/git/comcomai/blockchain/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
    Get API
      get_value api
        ✓ get_value
      get_function api
        ✓ get_function
      get_rule api
        ✓ get_rule
      get_owner api
        ✓ get_owner
      match_function api
        ✓ match_function
      match_rule api
        ✓ match_rule (write)
        ✓ match_rule api - state only
        ✓ match_rule api - state & write
      match_owner api
        ✓ match_owner
      eval_rule api
        ✓ eval_rule returning true
        ✓ eval_rule returning false
      eval_owner api
        ✓ eval_owner
      /get api
        ✓ get
      get_state_proof api
        ✓ get_state_proof
      get_proof_hash api
        ✓ get_proof_hash
      get_state_info api
        ✓ get_state_info
      get_state_usage api
        ✓ get_state_usage with existing app name
        ✓ get_state_usage with non-existing app name
      ain_get api
        ✓ returns the correct value
        ✓ returns error when invalid op_list is given
        ✓ returns error when requested data exceeds the get response limits (bytes) (6490ms)
        ✓ returns error when requested data exceeds the get response limits (siblings) (4298ms)
      ain_matchFunction api
        ✓ returns correct value
      ain_matchRule api
        ✓ returns correct value (write)
        ✓ returns correct value (state)
        ✓ returns correct value (state & write)
      ain_matchOwner api
        ✓ returns correct value
      ain_evalRule api
        ✓ returns true
        ✓ returns false
      ain_evalOwner api
        ✓ returns correct value
      ain_getStateProof api
        ✓ returns correct value
      ain_getProofHash api
        ✓ returns correct value
      ain_getStateInfo api
        ✓ returns correct value
      ain_getStateUsage api
        ✓ with existing app name
        ✓ with non-existing app name
      ain_getProtocolVersion api
        ✓ returns the correct version
      ain_checkProtocolVersion api
        ✓ returns success code
        ✓ returns version not specified code
        ✓ returns invalid version code
        ✓ returns incompatible version code for ill-formatted version
        ✓ returns incompatible version code for low version
      ain_getAddress api
        ✓ returns the correct node address
    Set API
      set_value api
        ✓ set_value (4207ms)
        ✓ set_value with timestamp (5232ms)
        ✓ set_value with nonce unordered (-1) (5240ms)
        ✓ set_value with numbered nonce (4233ms)
        ✓ set_value with failing operation (4228ms)
      inc_value api
        ✓ inc_value (4200ms)
        ✓ inc_value with a failing operation (6299ms)
      dec_value api
        ✓ dec_value (4219ms)
        ✓ dec_value with a failing operation (12556ms)
      set_function api
        ✓ set_function (5302ms)
        ✓ set_function with a failing operation (4223ms)
      set_rule api
        ✓ set_rule (3169ms)
        ✓ set_rule with a failing operation (5295ms)
      set_owner api
        ✓ set_owner (4369ms)
        ✓ set_owner with a failing operation (7401ms)
      set api
        ✓ set with successful operations (4211ms)
        ✓ set with a failing operation (7331ms)
        ✓ set with op_list size bigger than set_op_list_size_limit (3167ms)
      batch api
Iteration count exceeded its limit before the given tx 0x8278e09c7d3766f7b8c809c16bd326c6746355fbcbfc3a7f40f0438ef9974d06 is finalized!
Failed to check finalization of tx.
        1) batch with successful transactions
Iteration count exceeded its limit before the given tx 0xc5a477357e8ff3d9ff0dc391b8872193331535b9db23d2aec193ce1f9ed3fcfe is finalized!
Failed to check finalization of tx.
        2) batch with a failing transaction
      ain_sendSignedTransaction api
        ✓ accepts a transaction with nonce unordered (-1)
        ✓ accepts a transaction with numbered nonce
        ✓ rejects a transaction that exceeds its size limit.
        ✓ rejects a transaction of missing properties.
        ✓ rejects a transaction in an invalid format.
        ✓ rejects a transaction with an invalid signature.
      ain_sendSignedTransactionBatch api
        ✓ accepts a batch transaction
        ✓ rejects a batch transaction of invalid batch transaction format.
        3) accepts a batch transaction of under transaction list size limit.
        ✓ rejects a batch transaction of over transaction list size limit.
        4) rejects batch transactions that cause over per-account transaction pool size limit.
        ✓ rejects a batch transaction with a transaction that exceeds its size limit.
        ✓ rejects a batch transaction of missing transaction properties.
        ✓ rejects a batch transaction of invalid transaction format.
        ✓ rejects a batch transaction with an invalid signature.
    Billing
      ✓ app txs are not charged by transfer (11598ms)
      ✓ app-dependent service tx: individual account (4184ms)
      ✓ app-dependent service tx: invalid billing param
      ✓ app-dependent service tx: not a billing account user
      ✓ app-dependent service tx: billing account (4206ms)
      ✓ app-independent service tx: individual account (4184ms)
      ✓ app-independent service tx: billing account (4169ms)
      ✓ multi-set service tx: individual account (4189ms)
      ✓ multi-set service tx: billing account (4215ms)
      ✓ multi-set service tx: multiple apps (7346ms)
    Tx Receipts
      5) records a transaction receipt
      6) failed transaction


  83 passing (12m)
  6 failing

  1) Blockchain Node
       Set API
         batch api
           batch with successful transactions:

      AssertionError: expected [ Array(7) ] to deeply equal [ Array(7) ]
      + expected - actual

           "tx_hash": "erased"
         }
         {
           "result": {
      -      "bandwidth_gas_amount": 0
      -      "code": 10716
      -      "message": "[executeTransactionAndAddToPool] Tx pool does NOT have enough free room (10) for account: 0x00ADEc28B6a845a085e03591bE7550dd68673C1C"
      +      "gas_amount_charged": 0
      +      "gas_amount_total": {
      +        "bandwidth": {
      +          "app": {
      +            "test": 6
      +          }
      +          "service": 0
      +        }
      +        "state": {
      +          "app": {
      +            "test": 4388
      +          }
      +          "service": 0
      +        }
      +      }
      +      "gas_cost_total": 0
      +      "result_list": {
      +        "0": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "1": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "2": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "3": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "4": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "5": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +      }
           }
           "tx_hash": "erased"
         }
       ]
      
      at Context.<anonymous> (test/integration/node.test.js:2376:16)

  2) Blockchain Node
       Set API
         batch api
           batch with a failing transaction:

      AssertionError: expected [ Array(8) ] to deeply equal [ Array(8) ]
      + expected - actual

           "tx_hash": "erased"
         }
         {
           "result": {
      -      "bandwidth_gas_amount": 0
      -      "code": 10716
      -      "message": "erased"
      +      "gas_amount_charged": 0
      +      "gas_amount_total": {
      +        "bandwidth": {
      +          "app": {
      +            "test": 6
      +          }
      +          "service": 0
      +        }
      +        "state": {
      +          "app": {
      +            "test": 4388
      +          }
      +          "service": 0
      +        }
      +      }
      +      "gas_cost_total": 0
      +      "result_list": {
      +        "0": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "1": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "2": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "3": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "4": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +        "5": {
      +          "bandwidth_gas_amount": 1
      +          "code": 0
      +        }
      +      }
           }
           "tx_hash": "erased"
         }
       ]
      
      at Context.<anonymous> (test/integration/node.test.js:2757:16)

  3) Blockchain Node
       Set API
         ain_sendSignedTransactionBatch api
           accepts a batch transaction of under transaction list size limit.:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at /Users/seo/git/comcomai/blockchain/ain-blockchain/test/integration/node.test.js:3552:68
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  4) Blockchain Node
       Set API
         ain_sendSignedTransactionBatch api
           rejects batch transactions that cause over per-account transaction pool size limit.:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (test/integration/node.test.js:3635:69)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  5) Blockchain Node
       Tx Receipts
         records a transaction receipt:
     TypeError: Cannot read property 'address' of null
      at Context.<anonymous> (test/integration/node.test.js:4324:32)

  6) Blockchain Node
       Tx Receipts
         failed transaction:

      AssertionError: expected null to not equal null
      + expected - actual


      at Context.<anonymous> (test/integration/node.test.js:4364:30)



error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@ehgmsdk20 , could you take a look? It seems it's due to the tx pool limit changes.
- https://github.com/ainblockchain/ain-blockchain/pull/989

If not, please let us know.
fyi, you can try to use the dev-test instances for fast debugging.

cc: @liayoo

**Comment by ehgmsdk20** [comment]
I revised modified it not to limit free tx pool in test.
The test succeed with the disable_tx_receipt_recording timer flag turned off.
However, with the the disable_tx_receipt_recording timer flag turned on:
`"disable_tx_receipt_recording": {
    "enabled_block": 2,
    "has_bandage": false,
    "_note": "Remove this flag or set disabled_block to 2 if you need to run with the tx receipt recording feature"
  }`
  Error messages:
  `yarn run v1.22.17
$ BLOCKCHAIN_CONFIGS_DIR=blockchain-configs/3-nodes ./node_modules/mocha/bin/mocha --timeout 640000 test/integration/node.test.js
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /home/doheun/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /home/doheun/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /home/doheun/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /home/doheun/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /home/doheun/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording


  Blockchain Node
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /home/doheun/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /home/doheun/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /home/doheun/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /home/doheun/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /home/doheun/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /home/doheun/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /home/doheun/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /home/doheun/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /home/doheun/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /home/doheun/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /home/doheun/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /home/doheun/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /home/doheun/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /home/doheun/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /home/doheun/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
[createTimerFlagEnabledBandageMap] Registering bandage files:
[createTimerFlagEnabledBandageMap] [0] Registering /home/doheun/ain-blockchain/db/bandage-files/allow_lower_case_app_names_only.js
[createTimerFlagEnabledBandageMap] [1] Registering /home/doheun/ain-blockchain/db/bandage-files/create_app_config_sanitization.js
[createTimerFlagEnabledBandageMap] [2] Registering /home/doheun/ain-blockchain/db/bandage-files/native_service_path_length_check.js
[createTimerFlagEnabledBandageMap] [3] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte.js
[createTimerFlagEnabledBandageMap] [4] Registering /home/doheun/ain-blockchain/db/bandage-files/staking_balance_total_sum.js
[createTimerFlagEnabledBandageMap] [5] Registering /home/doheun/ain-blockchain/db/bandage-files/update_max_state_tree_size_per_byte2.js
[createTimerFlagEnabledBandageMap] [6] Registering /home/doheun/ain-blockchain/db/bandage-files/update_bandwidth_budget_params.js
[createTimerFlagEnabledBandageMap] [7] Skipping for timer flag: disable_tx_receipt_recording
    Get API
      get_value api
        ✓ get_value
      get_function api
        ✓ get_function
      get_rule api
        ✓ get_rule
      get_owner api
        ✓ get_owner
      match_function api
        ✓ match_function
      match_rule api
        ✓ match_rule (write)
        ✓ match_rule api - state only
        ✓ match_rule api - state & write
      match_owner api
        ✓ match_owner
      eval_rule api
        ✓ eval_rule returning true
        ✓ eval_rule returning false
      eval_owner api
        ✓ eval_owner
      /get api
        ✓ get
      get_state_proof api
        ✓ get_state_proof
      get_proof_hash api
        ✓ get_proof_hash
      get_state_info api
        ✓ get_state_info
      get_state_usage api
        ✓ get_state_usage with existing app name
        ✓ get_state_usage with non-existing app name
      ain_get api
        ✓ returns the correct value
        ✓ returns error when invalid op_list is given
        ✓ returns error when requested data exceeds the get response limits (bytes) (10264ms)
        ✓ returns error when requested data exceeds the get response limits (siblings) (4432ms)
      ain_matchFunction api
        ✓ returns correct value
      ain_matchRule api
        ✓ returns correct value (write)
        ✓ returns correct value (state)
        ✓ returns correct value (state & write)
      ain_matchOwner api
        ✓ returns correct value
      ain_evalRule api
        ✓ returns true
        ✓ returns false
      ain_evalOwner api
        ✓ returns correct value
      ain_getStateProof api
        ✓ returns correct value
      ain_getProofHash api
        ✓ returns correct value
      ain_getStateInfo api
        ✓ returns correct value
      ain_getStateUsage api
        ✓ with existing app name
        ✓ with non-existing app name
      ain_getProtocolVersion api
        ✓ returns the correct version
      ain_checkProtocolVersion api
        ✓ returns success code
        ✓ returns version not specified code
        ✓ returns invalid version code
        ✓ returns incompatible version code for ill-formatted version
        ✓ returns incompatible version code for low version
      ain_getAddress api
        ✓ returns the correct node address
    Set API
      set_value api
        ✓ set_value (4167ms)
        ✓ set_value with timestamp (4172ms)
        ✓ set_value with nonce unordered (-1) (4162ms)
        ✓ set_value with numbered nonce (4177ms)
        ✓ set_value with failing operation (14520ms)
      inc_value api
        ✓ inc_value (4156ms)
        ✓ inc_value with a failing operation (4163ms)
      dec_value api
        ✓ dec_value (4157ms)
        ✓ dec_value with a failing operation (8356ms)
      set_function api
        ✓ set_function (4173ms)
        ✓ set_function with a failing operation (6270ms)
      set_rule api
        ✓ set_rule (4202ms)
        ✓ set_rule with a failing operation (3129ms)
      set_owner api
        ✓ set_owner (4159ms)
        ✓ set_owner with a failing operation (5255ms)
      set api
        ✓ set with successful operations (4176ms)
        ✓ set with a failing operation (5266ms)
        ✓ set with op_list size bigger than set_op_list_size_limit (5222ms)
      batch api
        ✓ batch with successful transactions (10493ms)
        ✓ batch with a failing transaction (11483ms)
      ain_sendSignedTransaction api
        ✓ accepts a transaction with nonce unordered (-1)
        ✓ accepts a transaction with numbered nonce
        ✓ rejects a transaction that exceeds its size limit.
        ✓ rejects a transaction of missing properties.
        ✓ rejects a transaction in an invalid format.
        ✓ rejects a transaction with an invalid signature.
      ain_sendSignedTransactionBatch api
        ✓ accepts a batch transaction
        ✓ rejects a batch transaction of invalid batch transaction format. (70ms)
        ✓ accepts a batch transaction of under transaction list size limit. (100ms)
        ✓ rejects a batch transaction of over transaction list size limit.
        ✓ rejects batch transactions that cause over per-account transaction pool size limit. (264ms)
        ✓ rejects a batch transaction with a transaction that exceeds its size limit.
        ✓ rejects a batch transaction of missing transaction properties.
        ✓ rejects a batch transaction of invalid transaction format.
        ✓ rejects a batch transaction with an invalid signature.
    Billing
      ✓ app txs are not charged by transfer (14768ms)
      ✓ app-dependent service tx: individual account (5201ms)
      ✓ app-dependent service tx: invalid billing param
      ✓ app-dependent service tx: not a billing account user
      ✓ app-dependent service tx: billing account (4174ms)
      ✓ app-independent service tx: individual account (4237ms)
      ✓ app-independent service tx: billing account (4252ms)
      ✓ multi-set service tx: individual account (5194ms)
      ✓ multi-set service tx: billing account (5194ms)
      ✓ multi-set service tx: multiple apps (7409ms)
    Tx Receipts
      1) records a transaction receipt
      2) failed transaction


  87 passing (9m)
  2 failing

  1) Blockchain Node
       Tx Receipts
         records a transaction receipt:
     TypeError: Cannot read properties of null (reading 'address')
      at Context.<anonymous> (test/integration/node.test.js:4326:32)

  2) Blockchain Node
       Tx Receipts
         failed transaction:

      AssertionError: expected null to not equal null
      + expected - actual


      at Context.<anonymous> (test/integration/node.test.js:4366:30)



info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by platfowner** [comment]
@liayoo , could you take a look at the receipts-related test cases?

**Comment by platfowner** [comment]
Thanks for fixing it! @ehgmsdk20 @liayoo
